version: "3.8"
services:
  web246:
    container_name: web246
    build:
      context: .
    working_dir: /var/www/src
    volumes:
       - ./src:/var/www/src
       #- ./docker/index.php:/var/www/src/pub/index.php
       #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - ./env/magento.env  
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      
  mariadb:
    container_name: magento-mariadb
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER:  magento 
      MYSQL_PASSWORD: magento@123
      MYSQL_DATABASE : mage246_dev
    expose:
        - "40000"
    ports:
        - "40000:3306"
    volumes:
     - mariadb:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    env_file: ./env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306    

volumes:
  mariadb:
  opensearch-data:
